- name: Adicionar repositório do InfluxDB
  apt_repository:
    repo: "deb https://repos.influxdata.com/debian stable stable"
    state: present

- name: Baixar e instalar a chave do repositório do InfluxDB
  apt_key:
    url: "https://repos.influxdata.com/influxdb.key"
    state: present

- name: Instalar o InfluxDB
  apt:
    name: influxdb
    state: present
    update_cache: yes

- name: Iniciar o serviço do InfluxDB
  service:
    name: influxdb
    state: started
    enabled: yes

- name: Verificar a instalação do InfluxDB
  command: influxd version
  register: influxdb_version_output

- name: Mostrar a versão do InfluxDB
  debug:
    msg: "A versão do InfluxDB instalada é: {{ influxdb_version_output.stdout }}"
