- name: Baixar o binário do k6
  get_url:
    url: "https://github.com/grafana/k6/releases/download/{{ k6_version }}/k6-{{ k6_version }}-linux-amd64.tar.gz"
    dest: /tmp/k6-{{ k6_version }}-linux-amd64.tar.gz

- name: Extrair o arquivo tar.gz do k6
  unarchive:
    src: /tmp/k6-{{ k6_version }}-linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Mover o binário do k6 para /usr/local/bin
  command: mv /tmp/k6-{{ k6_version }}-linux-amd64/k6 /usr/local/bin/k6

- name: Garantir que o binário do k6 tenha permissões de execução
  file:
    path: /usr/local/bin/k6
    mode: '0755'

- name: Verificar a instalação do k6
  command: k6 version
  register: k6_version_output

- name: Mostrar a versão do k6
  debug:
    msg: "A versão do k6 instalada é: {{ k6_version_output.stdout }}"
