---
- name: Instalar k6 e Serverest
  hosts: k6, serverest
  become: true
  vars:
    k6_version: "v0.57.0"
    prometheus_version: "v2.45.0"
    node_exporter_version: "v1.6.1"

  tasks:
    - name: Atualizar o apt
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true

    - name: Atualizar pacotes e dependências
      apt:
        upgrade: yes
        cache_valid_time: 3600
      become: true

    - name: Instalar Node.js e npm (necessário para o npx) no Serverest
      apt:
        name:
          - nodejs
          - npm
        state: present
      when: inventory_hostname == "serverest"

    - name: Debug do nome do host
      debug:
        msg: "O nome do host é {{ inventory_hostname }}"

    - name: Instalar k6 via binário no host k6
      include_tasks: install_k6.yml
      when: inventory_hostname == "k6"

    - name: Instalar Prometheus e Node Exporter em todos os hosts
      include_tasks: install_prometheus_node_exporter.yml

    - name: Instalar Serverest via npm no host Serverest
      include_tasks: install_serverest.yml
      when: inventory_hostname == "serverest"

    - name: Copiar arquivos para a instância AWS no host k6
      copy:
        src: /home/rfahham/projetos/testes-performance/testes/serverest
        dest: /tmp/serverest
        mode: '0755'
        remote_src: no
      when: inventory_hostname == "k6"

- name: Instalar InfluxDB
  hosts: k6
  become: true
  tasks:
    - name: Adicionar repositório do InfluxDB
      apt_repository:
        repo: "deb https://repos.influxdata.com/debian stable stable"
        state: present

    - name: Baixar e instalar a chave do repositório do InfluxDB
      apt_key:
        url: "https://repos.influxdata.com/influxdb.key"
        state: present

    - name: Atualizar o apt após adicionar repositório do InfluxDB
      apt:
        update_cache: yes

    - name: Instalar o InfluxDB
      apt:
        name: influxdb
        state: present
        update_cache: yes

    - name: Iniciar o serviço do InfluxDB
      service:
        name: influxdb
        state: started
        enabled: yes

    - name: Verificar a instalação do InfluxDB
      command: influxd version
      register: influxdb_version_output

    - name: Mostrar a versão do InfluxDB
      debug:
        msg: "A versão do InfluxDB instalada é: {{ influxdb_version_output.stdout }}"


- name: Instalar Grafana
  hosts: grafana
  become: true
  tasks:
    - name: Baixar a chave GPG do repositório Grafana
      apt_key:
        url: "https://packages.grafana.com/gpg.key"
        state: present

    - name: Adicionar o repositório do Grafana
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Atualizar o apt e instalar o Grafana
      apt:
        update_cache: yes
        name: grafana
        state: present

    - name: Iniciar e habilitar o serviço Grafana
      service:
        name: grafana-server
        state: started
        enabled: yes

    - name: Verificar a instalação do Grafana
      command: grafana-server -v
      register: grafana_version

    - name: Mostrar a versão do Grafana
      debug:
        msg: "A versão do Grafana instalada é: {{ grafana_version.stdout }}"
